import type { Scenario } from '../types';
import { CALL_SCENARIOS } from './calls';
import { PASSERBY_IDS } from './npcs';
import { ROMANCE_SCENARIOS } from './romance';
import { obj, ph, STORY_SCENARIOS } from './story';

const PLACE_SCENARIOS: readonly Scenario[] = [
  {
    id: 'lost_luggage', kind: 'place', placeId: 'airport', npcId: 'nina',
    title: { en: 'Lost Luggage', ko: '사라진 수하물' },
    brief: { en: "Your suitcase never came out on the baggage belt. Report it and arrange delivery.", ko: '수하물 벨트에서 가방이 나오지 않았어요. 분실 신고를 하고 배송을 요청하세요.' },
    playerRole: 'a passenger whose suitcase did not arrive on flight EA 202',
    setting: 'The baggage service desk at Elden International Airport.',
    npcBrief: 'Follow procedure: flight number, bag description (color, size, brand, tags), valuable contents, and a delivery address and phone number. The bag is probably still at the previous airport; promise delivery within 24 hours. Offer a $50 voucher for toiletries if they ask about compensation.',
    opening: { en: "Hi there, baggage services. Let me guess — your bag didn't show up?", ko: '안녕하세요, 수하물 서비스입니다. 혹시… 가방이 안 나왔나요?' },
    objectives: [
      obj('o1', 'Give your flight number', '항공편 번호 말하기', 'The learner gives the flight number or flight details.'),
      obj('o2', 'Describe your suitcase', '가방 묘사하기', 'The learner describes the suitcase (color, size or features).'),
      obj('o3', 'Give a delivery address', '배송 주소 알려 주기', 'The learner gives an address or hotel for delivery.'),
      obj('b1', 'Ask for compensation', '보상 요청하기', 'The learner asks about compensation, a voucher or reimbursement.', true),
    ],
    phrases: [
      ph("My suitcase didn't come out.", '제 가방이 안 나왔어요.'),
      ph("It's a large black suitcase with a red tag.", '빨간 태그가 달린 큰 검은색 가방이에요.'),
      ph('I was on flight EA 202.', 'EA 202편을 타고 왔어요.'),
      ph('Could you deliver it to my hotel?', '호텔로 보내 주실 수 있나요?'),
      ph('Is there any compensation?', '보상이 있나요?'),
    ],
    maxTurns: 10, difficulty: 1, reward: { cash: 120, xp: 90 },
  },
  {
    id: 'cafe_order', kind: 'place', placeId: 'cafe', npcId: 'mia',
    title: { en: 'Morning Rush', ko: '아침 러시' },
    brief: { en: "It's the morning rush. Order a drink (and maybe a snack) exactly the way you like it — quickly!", ko: '출근 시간이라 붐벼요. 원하는 음료(와 간식)를 원하는 대로, 빠르게 주문하세요!' },
    playerRole: 'a customer ordering at the counter',
    setting: 'Bean There Café at 8 a.m., a long line and loud espresso machines.',
    npcBrief: 'Take the order quickly: drink, size, hot or iced, milk, name for the cup, for here or to go. Upsell a pastry once. Oat milk is sold out today — offer almond or soy instead. The total is around $6 to $9.',
    opening: { en: 'Hi! Welcome to Bean There. What can I get started for you?', ko: '안녕하세요! 빈 데어에 오신 걸 환영해요. 뭘로 준비해 드릴까요?' },
    objectives: [
      obj('o1', 'Order a drink with a size', '사이즈와 함께 음료 주문하기', 'The learner orders a drink and specifies the size.'),
      obj('o2', 'Answer a customization question', '옵션 질문에 답하기', 'The learner answers at least one customization question (hot/iced, milk, etc.).'),
      obj('o3', 'Pay and finish the order', '결제하고 주문 마무리하기', 'The learner pays or confirms payment (card or cash).'),
      obj('b1', 'Order a snack too', '간식도 주문하기', 'The learner also orders food (pastry, muffin, etc.).', true),
    ],
    phrases: [
      ph('Can I get a large iced latte, please?', '아이스 라떼 라지로 주시겠어요?'),
      ph('Could I have it with almond milk?', '아몬드 우유로 해 주실 수 있나요?'),
      ph('To go, please.', '포장해 주세요.'),
      ph("I'll pay by card.", '카드로 계산할게요.'),
      ph('What do you recommend?', '뭐가 맛있어요?'),
    ],
    maxTurns: 8, difficulty: 1, reward: { cash: 80, xp: 70 },
  },
  {
    id: 'cafe_wrong_order', kind: 'place', placeId: 'cafe', npcId: 'mia',
    title: { en: 'Wrong Order', ko: '잘못 나온 음료' },
    brief: { en: 'You ordered an iced vanilla latte but got a hot caramel macchiato. Politely get it fixed.', ko: '아이스 바닐라 라떼를 시켰는데 따뜻한 카라멜 마키아토가 나왔어요. 정중하게 바꿔 달라고 하세요.' },
    playerRole: 'a customer who received the wrong drink',
    setting: 'The pickup counter at Bean There Café; Mia is juggling ten orders.',
    npcBrief: "At first you think the drink is correct (the receipt is confusing). Ask what they ordered. Once they explain clearly and politely, apologize, remake it and offer a free cookie. If they are rude, be cold but still fix it.",
    opening: { en: 'Caramel macchiato for… {player}? Here you go! Enjoy!', ko: '카라멜 마키아토… {player} 님? 여기 있어요! 맛있게 드세요!' },
    objectives: [
      obj('o1', 'Explain the problem politely', '정중하게 문제 설명하기', 'The learner politely explains that the drink is wrong.'),
      obj('o2', 'Say what you actually ordered', '원래 주문한 음료 말하기', 'The learner says what they originally ordered (an iced vanilla latte).'),
      obj('o3', 'Get it remade', '다시 만들어 달라고 하기', 'The barista agrees to remake the drink.'),
      obj('b1', 'Accept the apology gracefully', '사과를 기분 좋게 받아 주기', "The learner responds kindly to the apology (e.g. 'No worries')." , true),
    ],
    phrases: [
      ph("Sorry, I think there's been a mix-up.", '죄송한데, 주문이 바뀐 것 같아요.'),
      ph('I actually ordered an iced vanilla latte.', '저는 아이스 바닐라 라떼를 시켰어요.'),
      ph('Could you remake it, please?', '다시 만들어 주실 수 있나요?'),
      ph('No worries, it happens.', '괜찮아요, 그럴 수 있죠.'),
    ],
    maxTurns: 8, difficulty: 1, reward: { cash: 90, xp: 80 },
  },
  {
    id: 'hotel_room_issue', kind: 'place', placeId: 'hotel', npcId: 'priya',
    title: { en: 'Room Trouble', ko: '객실 문제' },
    brief: { en: "Your air conditioner is broken and the neighbors are loud. Complain politely and get a better room.", ko: '에어컨이 고장 났고 옆방이 너무 시끄러워요. 정중하게 항의해서 더 나은 방을 받아 내세요.' },
    playerRole: 'a hotel guest in room 1208 with a broken air conditioner and noisy neighbors',
    setting: 'The Grand Elden Hotel front desk at 11 p.m.',
    npcBrief: 'Apologize. First offer to send maintenance (it will take an hour). If the learner asks to change rooms, offer a quieter room on the 15th floor. If they are polite and persuasive, add a free breakfast.',
    opening: { en: 'Good evening. How may I assist you tonight?', ko: '안녕하세요. 오늘 밤 무엇을 도와드릴까요?' },
    objectives: [
      obj('o1', 'Describe the problems', '문제 설명하기', 'The learner describes at least one problem with the room (AC, noise).'),
      obj('o2', 'Give your room number', '방 번호 말하기', 'The learner gives their room number.'),
      obj('o3', 'Ask to change rooms', '방 변경 요청하기', 'The learner asks to move to a different room.'),
      obj('b1', 'Get something extra', '보상 받아 내기', 'The learner politely asks for compensation (discount, free breakfast, etc.) and gets it.', true),
    ],
    phrases: [
      ph("I'm afraid there's a problem with my room.", '죄송하지만 방에 문제가 있어요.'),
      ph("The air conditioner isn't working.", '에어컨이 안 돼요.'),
      ph('The people next door are really loud.', '옆방이 너무 시끄러워요.'),
      ph('Would it be possible to change rooms?', '방을 바꿀 수 있을까요?'),
      ph("I'd really appreciate it.", '그렇게 해 주시면 정말 감사하겠어요.'),
    ],
    maxTurns: 10, difficulty: 2, reward: { cash: 110, xp: 100 },
  },
  {
    id: 'bank_card_blocked', kind: 'place', placeId: 'bank', npcId: 'whitmore',
    title: { en: 'Card Blocked', ko: '카드 정지' },
    brief: { en: 'Your debit card was declined three times today. Find out why and get it working again.', ko: '오늘 체크카드 결제가 세 번이나 거절됐어요. 이유를 알아내고 다시 쓸 수 있게 하세요.' },
    playerRole: 'a bank customer whose debit card was blocked',
    setting: 'The customer service desk at Elden National Bank.',
    npcBrief: "The card was blocked for suspicious activity: a $900 purchase at 'Gadget World Online' last night. Verify identity (full name and date of birth), then ask if they made that purchase. If not, cancel the card and order a new one (3 to 5 days); if they did, unblock it.",
    opening: { en: 'Good morning. I understand there is an issue with your card?', ko: '안녕하세요. 카드에 문제가 있으시다고요?' },
    objectives: [
      obj('o1', 'Explain the problem with your card', '카드 문제 설명하기', 'The learner explains that their card was declined or blocked.'),
      obj('o2', 'Verify your identity', '본인 확인하기', 'The learner gives their full name and date of birth (or other ID details).'),
      obj('o3', 'Respond about the suspicious purchase', '의심 거래에 답하기', 'The learner says whether they made the suspicious purchase.'),
      obj('b1', 'Ask how to prevent it', '재발 방지 방법 묻기', 'The learner asks how to avoid this problem in the future.', true),
    ],
    phrases: [
      ph('My card keeps getting declined.', '카드가 계속 거절돼요.'),
      ph("I didn't make that purchase.", '그 결제는 제가 한 게 아니에요.'),
      ph('Could you unblock my card?', '카드 정지를 풀어 주실 수 있나요?'),
      ph('How long will a new card take?', '새 카드는 얼마나 걸려요?'),
    ],
    maxTurns: 10, difficulty: 2, reward: { cash: 110, xp: 100 },
  },
  {
    id: 'lost_wallet', kind: 'place', placeId: 'police', npcId: 'rosa',
    title: { en: 'Lost Wallet', ko: '지갑 분실' },
    brief: { en: 'You lost your wallet somewhere downtown. Report it and describe it.', ko: '다운타운 어딘가에서 지갑을 잃어버렸어요. 분실 신고를 하고 지갑을 묘사하세요.' },
    playerRole: 'someone who lost their wallet downtown',
    setting: 'The lost-and-found desk at ECPD Central Station.',
    npcBrief: 'Ask when and where they last had it, what it looks like and what was inside. A brown leather wallet was turned in this morning — if their description is close, return it after they confirm one detail (e.g. which cards were inside).',
    opening: { en: 'Lost and found. What did you lose today?', ko: '분실물 센터입니다. 오늘은 뭘 잃어버리셨어요?' },
    objectives: [
      obj('o1', 'Say what you lost', '잃어버린 물건 말하기', 'The learner says they lost their wallet.'),
      obj('o2', 'Describe the wallet', '지갑 묘사하기', 'The learner describes the wallet (color, material, size).'),
      obj('o3', 'Say where you last had it', '마지막으로 본 곳 말하기', 'The learner says where or when they last had it.'),
      obj('b1', 'Describe what was inside', '안에 든 것 말하기', 'The learner describes the contents (cards, cash, ID, photos).', true),
    ],
    phrases: [
      ph('I think I lost my wallet.', '지갑을 잃어버린 것 같아요.'),
      ph("It's a brown leather wallet.", '갈색 가죽 지갑이에요.'),
      ph('I last had it at a café on Market Street.', '마켓 스트리트 카페에서 마지막으로 있었어요.'),
      ph('My ID and two credit cards were inside.', '안에 신분증이랑 신용카드 두 장이 있었어요.'),
    ],
    maxTurns: 8, difficulty: 1, reward: { cash: 90, xp: 80 },
  },
  {
    id: 'diner_breakfast', kind: 'place', placeId: 'diner', npcId: 'dot',
    title: { en: 'Breakfast Special', ko: '아침 특선' },
    brief: { en: 'Order a classic American breakfast. Dot will have questions — lots of them.', ko: '클래식 아메리칸 브렉퍼스트를 주문하세요. 도트가 질문을… 아주 많이 할 거예요.' },
    playerRole: 'a hungry customer at a diner',
    setting: 'Harbor Diner at 7 a.m., fishermen at the counter.',
    npcBrief: "Recommend the Captain's Breakfast (eggs, bacon or sausage, toast, hash browns). Ask the typical diner questions: How would you like your eggs? White, wheat or rye toast? Bacon or sausage? Coffee refill? Chat a little about the weather and the docks.",
    opening: { en: "Mornin', hon! What'll it be today?", ko: '좋은 아침, 자기! 오늘은 뭐 먹을래?' },
    objectives: [
      obj('o1', 'Order a breakfast', '아침 메뉴 주문하기', 'The learner orders a breakfast dish.'),
      obj('o2', 'Say how you want your eggs', '달걀 조리법 말하기', 'The learner says how they want their eggs (scrambled, over easy, sunny side up, etc.).'),
      obj('o3', 'Choose your sides', '사이드 고르기', 'The learner chooses a toast type, bacon/sausage or another side.'),
      obj('b1', 'Make small talk with Dot', '도트와 수다 떨기', 'The learner makes small talk (asks about her day, the weather, the diner).', true),
    ],
    phrases: [
      ph("I'll have the Captain's Breakfast, please.", '캡틴스 브렉퍼스트 주세요.'),
      ph('Scrambled, please.', '스크램블로 해 주세요.'),
      ph('Wheat toast and bacon, please.', '통밀 토스트랑 베이컨으로 주세요.'),
      ph('Could I get a refill?', '리필 좀 해 주실래요?'),
    ],
    maxTurns: 9, difficulty: 1, reward: { cash: 80, xp: 70 },
  },
  {
    id: 'garage_repair', kind: 'place', placeId: 'garage', npcId: 'rusty',
    title: { en: 'Strange Noises', ko: '이상한 소리' },
    brief: { en: 'Your car squeaks when you brake. Describe the problem and get a fair price for the repair.', ko: '브레이크를 밟으면 차에서 끼익 소리가 나요. 문제를 설명하고 수리비를 적정하게 흥정하세요.' },
    playerRole: 'a driver whose car makes a squeaking noise when braking',
    setting: "Rusty's Garage, loud with power tools.",
    npcBrief: 'Ask what the noise sounds like, when it happens and since when. Diagnose worn brake pads. Quote $400 first (overpriced). If the learner questions the price or asks for a breakdown, lower it to $250 (parts $120 plus labor). Ready by tomorrow.',
    opening: { en: "Yeah? What's wrong with it this time?", ko: '어? 이번엔 또 뭐가 문젠데?' },
    objectives: [
      obj('o1', 'Describe the noise', '소리 묘사하기', 'The learner describes the noise (squeaking, grinding, etc.).'),
      obj('o2', 'Explain when it happens', '언제 나는지 설명하기', 'The learner explains when the noise happens (e.g. when braking).'),
      obj('o3', 'Ask about the cost', '비용 묻기', 'The learner asks how much the repair will cost.'),
      obj('b1', 'Negotiate a better price', '수리비 깎기', 'The learner questions the price or negotiates and gets it lowered.', true),
    ],
    phrases: [
      ph('It makes a squeaking noise when I brake.', '브레이크 밟으면 끼익 소리가 나요.'),
      ph('It started about a week ago.', '일주일 전쯤부터 그랬어요.'),
      ph('How much will it cost?', '비용이 얼마나 들까요?'),
      ph('That seems expensive. Could you break it down for me?', '좀 비싼데요. 내역을 알려 주실래요?'),
      ph('When will it be ready?', '언제 다 돼요?'),
    ],
    maxTurns: 10, difficulty: 2, reward: { cash: 120, xp: 100 },
  },
  {
    id: 'doctor_visit', kind: 'place', placeId: 'hospital', npcId: 'patel',
    title: { en: "Doctor's Visit", ko: '진료 받기' },
    brief: { en: "You've had a headache and a fever for two days. Describe your symptoms and understand the doctor's advice.", ko: '이틀째 두통과 열이 있어요. 증상을 설명하고 의사의 조언을 이해하세요.' },
    playerRole: 'a patient with a headache, fever and sore throat for two days',
    setting: "A quiet examination room at St. Mary's Hospital.",
    npcBrief: 'Ask about symptoms one at a time: what, since when, how bad (1 to 10), other symptoms, allergies, medication already taken. Diagnose a common flu. Advise rest, fluids and ibuprofen every 6 hours; come back if the fever stays above 39°C for more than three days. Check that they understood.',
    opening: { en: "Hello, I'm Dr. Patel. What seems to be the problem today?", ko: '안녕하세요, 파텔입니다. 오늘은 어디가 불편하세요?' },
    objectives: [
      obj('o1', 'Describe your main symptoms', '주요 증상 설명하기', 'The learner describes their symptoms (headache, fever, sore throat).'),
      obj('o2', 'Say how long you have had them', '증상 기간 말하기', 'The learner says how long they have had the symptoms.'),
      obj('o3', 'Answer about allergies or medication', '알레르기·복용 약 답하기', 'The learner answers a question about allergies or medication.'),
      obj('b1', "Check the doctor's instructions", '처방 내용 확인하기', 'The learner asks a question to confirm or clarify the treatment.', true),
    ],
    phrases: [
      ph("I've had a headache for two days.", '이틀째 머리가 아파요.'),
      ph('I have a fever and a sore throat.', '열이 나고 목이 아파요.'),
      ph("I'm not allergic to anything.", '알레르기는 없어요.'),
      ph('How often should I take it?', '얼마나 자주 먹어야 해요?'),
      ph("Should I come back if it doesn't get better?", '안 나으면 다시 와야 하나요?'),
    ],
    maxTurns: 10, difficulty: 2, reward: { cash: 110, xp: 100 },
  },
  {
    id: 'pharmacy_cold', kind: 'place', placeId: 'pharmacy', npcId: 'tom',
    title: { en: 'Cold Medicine', ko: '감기약 사기' },
    brief: { en: 'You have a runny nose and a cough. Get the right medicine and understand how to take it.', ko: '콧물과 기침이 나요. 알맞은 약을 사고 복용법을 이해하세요.' },
    playerRole: 'a customer with a cold (runny nose, cough) looking for medicine',
    setting: 'The CityCare Pharmacy counter.',
    npcBrief: "Ask about symptoms, how long, allergies, other medicine, and whether they need to drive (some medicine causes drowsiness). Recommend 'ColdAway Day & Night': day tablets twice a day, night tablet once before bed. Price $12.99.",
    opening: { en: 'Hi there! What can I help you find today?', ko: '안녕하세요! 오늘 어떤 걸 찾으세요?' },
    objectives: [
      obj('o1', 'Describe your symptoms', '증상 말하기', 'The learner describes cold symptoms.'),
      obj('o2', 'Answer the safety questions', '안전 질문에 답하기', 'The learner answers about allergies, other medicine or driving.'),
      obj('o3', 'Ask how to take the medicine', '복용법 묻기', 'The learner asks about dosage or how to take the medicine.'),
      obj('b1', 'Ask about side effects', '부작용 묻기', 'The learner asks about side effects (e.g. drowsiness).', true),
    ],
    phrases: [
      ph("I've got a runny nose and a bad cough.", '콧물이 나고 기침이 심해요.'),
      ph('Do you have anything for a cold?', '감기약 있나요?'),
      ph('Will it make me drowsy?', '먹으면 졸려요?'),
      ph('How many should I take a day?', '하루에 몇 알 먹어야 해요?'),
    ],
    maxTurns: 8, difficulty: 1, reward: { cash: 90, xp: 80 },
  },
  {
    id: 'restaurant_order', kind: 'place', placeId: 'restaurant', npcId: 'marco',
    title: { en: "Dinner at Luigi's", ko: '루이지에서 저녁을' },
    brief: { en: "Order dinner, ask for a recommendation, and make sure the waiter knows you're allergic to shellfish.", ko: '저녁을 주문하고, 추천을 받고, 갑각류 알레르기가 있다는 걸 꼭 알리세요.' },
    playerRole: 'a diner with a shellfish allergy',
    setting: "Luigi's Trattoria, candles on the tables and soft Italian music.",
    npcBrief: "Welcome them with passion. Tonight's specials: seafood linguine (contains shrimp!), mushroom risotto and osso buco. Take orders for a drink and a main dish and recommend tiramisu. If they mention the allergy, take it seriously and suggest safe dishes. If they order the seafood linguine without mentioning it, ask 'Any allergies I should know about?'.",
    opening: { en: "Buonasera! Welcome to Luigi's. Can I start you off with something to drink?", ko: '부오나세라! 루이지에 오신 걸 환영합니다. 음료부터 준비해 드릴까요?' },
    objectives: [
      obj('o1', 'Order a drink', '음료 주문하기', 'The learner orders a drink.'),
      obj('o2', 'Mention your shellfish allergy', '갑각류 알레르기 알리기', 'The learner clearly mentions a shellfish allergy.'),
      obj('o3', 'Order a main course', '메인 요리 주문하기', 'The learner orders a main dish.'),
      obj('b1', 'Ask for a recommendation', '추천 받기', 'The learner asks the waiter to recommend something.', true),
    ],
    phrases: [
      ph("I'll have sparkling water, please.", '탄산수 주세요.'),
      ph('What would you recommend?', '뭘 추천하세요?'),
      ph("I'm allergic to shellfish.", '저 갑각류 알레르기가 있어요.'),
      ph('Does this dish contain shrimp?', '이 요리에 새우 들어가요?'),
      ph("I'll go with the mushroom risotto.", '버섯 리소토로 할게요.'),
    ],
    maxTurns: 10, difficulty: 2, reward: { cash: 110, xp: 100 },
  },
  {
    id: 'restaurant_bill', kind: 'place', placeId: 'restaurant', npcId: 'marco',
    title: { en: 'Check, Please!', ko: '계산서 주세요!' },
    brief: { en: "Your bill has a $28 lobster ravioli that nobody ordered. Get it removed and split the bill with your friend.", ko: '계산서에 아무도 안 시킨 28달러짜리 랍스터 라비올리가 있어요. 빼 달라고 하고 친구와 나눠서 계산하세요.' },
    playerRole: 'a diner paying for themselves and a friend; the bill wrongly includes a $28 lobster ravioli',
    setting: "Luigi's Trattoria at the end of the evening.",
    npcBrief: 'Bring the check proudly. When the learner points out the lobster ravioli, first insist it was ordered, then check with the kitchen and apologize and remove it. Ask how they want to pay: together or separately, cash or card. Tipping 15–20% is customary.',
    opening: { en: "I hope everything was bellissimo! Here's your check. No rush!", ko: '모든 게 벨리시모였길 바랍니다! 계산서 여기 있어요. 천천히 하세요!' },
    objectives: [
      obj('o1', 'Point out the mistake', '실수 지적하기', 'The learner points out the incorrect item on the bill.'),
      obj('o2', 'Get the item removed', '항목 빼기', 'The waiter agrees to remove the incorrect item.'),
      obj('o3', 'Ask to split the bill', '나눠 계산 요청하기', 'The learner asks to split the bill or pay separately.'),
      obj('b1', 'Leave a tip', '팁 남기기', 'The learner mentions or leaves a tip.', true),
    ],
    phrases: [
      ph("I think there's a mistake on the bill.", '계산서에 착오가 있는 것 같아요.'),
      ph("We didn't order the lobster ravioli.", '저희 랍스터 라비올리 안 시켰어요.'),
      ph('Could we split the bill?', '나눠서 계산할 수 있을까요?'),
      ph('Keep the change.', '잔돈은 가지세요.'),
    ],
    maxTurns: 8, difficulty: 2, reward: { cash: 100, xp: 90 },
  },
  {
    id: 'market_find', kind: 'place', placeId: 'market', npcId: 'jen',
    title: { en: "Where's the…?", ko: '어디 있어요?' },
    brief: { en: 'You need eggs, olive oil and batteries. Ask the clerk where to find them.', ko: '계란, 올리브유, 건전지가 필요해요. 점원에게 어디 있는지 물어보세요.' },
    playerRole: 'a shopper looking for eggs, olive oil and AA batteries',
    setting: 'FreshMart supermarket, aisle 5. Jen is stocking cereal boxes.',
    npcBrief: 'Answer lazily at first, then more helpfully if the learner is friendly. Eggs: dairy section at the back. Olive oil: aisle 3 next to the pasta (buy one, get one free today). Batteries: at the checkout counter.',
    opening: { en: 'Hey. Um, can I help you find something?', ko: '안녕하세요. 음, 뭐 찾으세요?' },
    objectives: [
      obj('o1', 'Ask where the eggs are', '계란 위치 묻기', 'The learner asks where the eggs are.'),
      obj('o2', 'Ask where the olive oil is', '올리브유 위치 묻기', 'The learner asks where the olive oil is.'),
      obj('o3', 'Ask where the batteries are', '건전지 위치 묻기', 'The learner asks where the batteries are.'),
      obj('b1', 'Find out about a sale', '할인 정보 알아내기', 'The learner asks about discounts or reacts to the sale.', true),
    ],
    phrases: [
      ph('Excuse me, where can I find the eggs?', '실례지만, 계란은 어디 있어요?'),
      ph('Which aisle is the olive oil in?', '올리브유는 몇 번 통로에 있어요?'),
      ph('Do you sell batteries?', '건전지 팔아요?'),
      ph('Is anything on sale today?', '오늘 할인하는 거 있어요?'),
    ],
    maxTurns: 8, difficulty: 1, reward: { cash: 70, xp: 60 },
  },
  {
    id: 'gym_membership', kind: 'place', placeId: 'gym', npcId: 'chad',
    title: { en: 'No Pain, No Gain', ko: '헬스장 등록' },
    brief: { en: 'You want a gym membership, but Chad keeps pushing the most expensive plan. Find the plan that fits you and avoid hidden fees.', ko: '헬스장에 등록하려는데 채드가 계속 제일 비싼 요금제를 밀어요. 나에게 맞는 요금제를 찾고 숨은 비용을 피하세요.' },
    playerRole: 'someone who wants a basic gym membership on a budget',
    setting: 'The front desk of Iron Temple Gym, loud music and clanking weights.',
    npcBrief: "Push the 'Titan Plan' ($89/month, 24-month contract, personal training). Only mention the 'Basic Plan' ($29/month, no contract) if they ask for something cheaper. There's a $50 sign-up fee, which you waive if they negotiate. Cancellation needs 30 days' notice.",
    opening: { en: "Yo, welcome to Iron Temple, bro! Ready to transform your life? Let's go!", ko: '어이, 아이언 템플에 온 걸 환영해! 인생 바꿀 준비 됐어? 가자고!' },
    objectives: [
      obj('o1', 'Ask about membership options', '회원권 종류 묻기', 'The learner asks about membership plans or prices.'),
      obj('o2', 'Ask for a cheaper plan', '더 저렴한 요금제 요청하기', 'The learner asks for a cheaper or more basic option.'),
      obj('o3', 'Ask about the contract or cancellation', '약정·해지 조건 묻기', 'The learner asks about the contract length or how to cancel.'),
      obj('b1', 'Get the sign-up fee waived', '가입비 면제받기', 'The learner negotiates and gets the sign-up fee waived.', true),
    ],
    phrases: [
      ph('What membership options do you have?', '회원권 종류가 뭐가 있어요?'),
      ph('Do you have anything cheaper?', '더 싼 건 없어요?'),
      ph('Is there a contract?', '약정이 있나요?'),
      ph('Are there any hidden fees?', '숨은 비용이 있나요?'),
      ph('Could you waive the sign-up fee?', '가입비는 빼 주실 수 있어요?'),
    ],
    maxTurns: 10, difficulty: 2, reward: { cash: 110, xp: 100 },
  },
  {
    id: 'phone_plan', kind: 'place', placeId: 'techstore', npcId: 'kevin',
    title: { en: 'New Phone Plan', ko: '휴대폰 요금제' },
    brief: { en: 'You need a local SIM card and a data plan. Understand the options and choose one.', ko: '현지 유심과 데이터 요금제가 필요해요. 옵션을 이해하고 하나를 고르세요.' },
    playerRole: 'a newcomer who needs a local SIM card and data plan for their unlocked phone',
    setting: 'Pixel Tech Store, bright displays everywhere.',
    npcBrief: "Explain plans with too much jargon at first: 'Starter' 5GB $20/month, 'Plus' 20GB $35/month, 'Unlimited' $55/month (speeds throttled after 50GB). Explain simply if asked. Ask whether the phone is unlocked and whether they want prepaid or monthly. Activation needs ID.",
    opening: { en: 'Hey! Welcome to Pixel! Looking for a new phone or a plan today?', ko: '안녕하세요! 픽셀에 오신 걸 환영해요! 새 폰 보세요, 요금제 보세요?' },
    objectives: [
      obj('o1', 'Ask for a SIM card and plan', '유심과 요금제 요청하기', 'The learner asks for a SIM card or phone plan.'),
      obj('o2', 'Ask for a simpler explanation', '쉽게 설명해 달라고 하기', 'The learner asks the clerk to explain more simply or asks what a term means.'),
      obj('o3', 'Choose a plan', '요금제 고르기', 'The learner chooses one of the plans.'),
      obj('b1', 'Ask about international calls', '국제 전화 문의하기', 'The learner asks about calling or texting internationally.', true),
    ],
    phrases: [
      ph('I need a SIM card for my phone.', '제 폰에 넣을 유심이 필요해요.'),
      ph("Sorry, what does 'throttled' mean?", "죄송한데, 'throttled'가 무슨 뜻이에요?"),
      ph('Could you explain that in simpler terms?', '좀 더 쉽게 설명해 주실래요?'),
      ph("I'll go with the Plus plan.", '플러스 요금제로 할게요.'),
      ph('Does it include international calls?', '국제 전화도 포함돼요?'),
    ],
    maxTurns: 10, difficulty: 2, reward: { cash: 110, xp: 100 },
  },
  {
    id: 'broken_screen', kind: 'place', placeId: 'techstore', npcId: 'kevin',
    title: { en: 'Cracked Screen', ko: '액정 파손' },
    brief: { en: "Your new phone's screen cracked after one week. Convince the store to fix it under warranty.", ko: '새 폰 액정이 일주일 만에 깨졌어요. 보증으로 수리해 달라고 설득하세요.' },
    playerRole: 'a customer whose one-week-old phone screen cracked in their pocket without being dropped',
    setting: 'The repair counter at Pixel Tech Store.',
    npcBrief: "The warranty doesn't cover accidental damage, so first say the repair costs $180. If the learner explains clearly that it wasn't dropped, points out that it's only a week old and suggests a manufacturing defect, agree to a free inspection and offer a loaner phone.",
    opening: { en: 'Oof, that screen looks rough. What happened?', ko: '아이고, 액정이 심하게 깨졌네요. 무슨 일이에요?' },
    objectives: [
      obj('o1', 'Explain what happened', '상황 설명하기', 'The learner explains how the screen cracked.'),
      obj('o2', 'Mention the warranty', '보증 언급하기', 'The learner mentions the warranty or that the phone is new.'),
      obj('o3', 'Get a free repair or inspection', '무상 수리·점검 받아 내기', 'The clerk agrees to a free repair, inspection or replacement.'),
      obj('b1', 'Ask for a loaner phone', '임대폰 요청하기', 'The learner asks for a temporary phone.', true),
    ],
    phrases: [
      ph("I didn't drop it. It just cracked in my pocket.", '떨어뜨린 적 없어요. 주머니에서 그냥 깨졌어요.'),
      ph('I only bought it a week ago.', '산 지 일주일밖에 안 됐어요.'),
      ph("Isn't this covered by the warranty?", '이거 보증 적용 안 되나요?'),
      ph('Could it be a manufacturing defect?', '제조 결함일 수도 있지 않나요?'),
      ph('Can I borrow a phone in the meantime?', '그동안 쓸 폰을 빌릴 수 있을까요?'),
    ],
    maxTurns: 10, difficulty: 3, reward: { cash: 140, xp: 120 },
  },
  {
    id: 'boutique_fit', kind: 'place', placeId: 'boutique', npcId: 'elodie',
    title: { en: 'The Perfect Outfit', ko: '완벽한 옷 찾기' },
    brief: { en: 'You need an outfit for your first day at work. Ask about sizes and colors, and try something on.', ko: '출근 첫날 입을 옷이 필요해요. 사이즈와 색상을 묻고 옷을 입어 보세요.' },
    playerRole: 'a customer looking for smart-casual clothes for a new office job',
    setting: 'Maison Mode, a chic boutique with minimalist racks.',
    npcBrief: 'Ask about the occasion, their style and size. Suggest a navy blazer ($120) and a white shirt ($45). The blazer in their size only comes in black or navy. Fitting rooms are at the back. React with polite irony to odd choices, but help.',
    opening: { en: 'Bonjour. Welcome to Maison Mode. Looking for anything in particular?', ko: '봉주르. 메종 모드에 오신 걸 환영해요. 특별히 찾으시는 게 있나요?' },
    objectives: [
      obj('o1', 'Explain what you need', '필요한 옷 설명하기', 'The learner explains what clothes they need and for what occasion.'),
      obj('o2', 'Ask about size or color', '사이즈·색상 묻기', 'The learner asks about a size or color.'),
      obj('o3', 'Ask to try something on', '입어 봐도 되는지 묻기', 'The learner asks to try an item on.'),
      obj('b1', 'Ask for a discount', '할인 문의하기', 'The learner asks about a discount or sale.', true),
    ],
    phrases: [
      ph("I'm looking for something to wear to work.", '출근할 때 입을 옷을 찾고 있어요.'),
      ph('Do you have this in a medium?', '이거 미디엄 있어요?'),
      ph('Does it come in other colors?', '다른 색도 있어요?'),
      ph('Can I try this on?', '이거 입어 봐도 돼요?'),
      ph('Where are the fitting rooms?', '탈의실은 어디예요?'),
    ],
    maxTurns: 9, difficulty: 1, reward: { cash: 90, xp: 80 },
  },
  {
    id: 'boutique_return', kind: 'place', placeId: 'boutique', npcId: 'elodie',
    title: { en: 'Return a Gift', ko: '선물 반품' },
    brief: { en: 'Leo gave you a very… colorful sweater. Return it without a receipt and exchange it for something else.', ko: '레오가 준 스웨터가 너무… 화려해요. 영수증 없이 반품하고 다른 걸로 교환하세요.' },
    playerRole: 'a customer returning a gift sweater without a receipt (the tags are still attached)',
    setting: 'The Maison Mode checkout counter.',
    npcBrief: 'Store policy: refunds need a receipt, but exchanges or store credit are possible without one if the tags are attached. First say a receipt is required. If the learner politely explains it was a gift and asks about options, offer store credit. Make one ironic comment about the sweater.',
    opening: { en: 'Ah. That sweater. How can I help you with… that?', ko: '아. 그 스웨터군요. 그… 옷은 어떻게 도와드릴까요?' },
    objectives: [
      obj('o1', 'Say you want to return it', '반품 의사 밝히기', 'The learner says they want to return or exchange the sweater.'),
      obj('o2', 'Explain that it was a gift', '선물이었다고 설명하기', 'The learner explains it was a gift and they have no receipt.'),
      obj('o3', 'Get an exchange or store credit', '교환·적립금 받기', 'The learner gets an exchange or store credit.'),
      obj('b1', 'Stay polite about the policy', '규정에 예의 있게 대응하기', 'The learner politely accepts or negotiates the policy without being rude.', true),
    ],
    phrases: [
      ph("I'd like to return this sweater.", '이 스웨터 반품하고 싶어요.'),
      ph("It was a gift, so I don't have the receipt.", '선물 받은 거라 영수증이 없어요.'),
      ph('The tags are still on it.', '태그는 그대로 붙어 있어요.'),
      ph('Could I exchange it instead?', '대신 교환은 될까요?'),
      ph('Store credit is fine.', '적립금으로 받아도 돼요.'),
    ],
    maxTurns: 8, difficulty: 2, reward: { cash: 100, xp: 90 },
  },
  {
    id: 'apartment_hunt', kind: 'place', placeId: 'realty', npcId: 'brenda',
    title: { en: 'Apartment Hunting', ko: '집 구하기' },
    brief: { en: "Time to leave the hotel! Ask about an apartment's rent, deposit, utilities and rules — and find out what Brenda isn't telling you.", ko: '호텔을 떠날 시간! 아파트의 월세, 보증금, 공과금, 규칙을 물어보고 브렌다가 숨기는 게 뭔지 알아내세요.' },
    playerRole: 'someone looking for a one-bedroom apartment for under $1,500 per month',
    setting: 'The Skyline Realty office, apartment photos on every wall.',
    npcBrief: "Show 'a cozy, charming one-bedroom on Elm Street': rent $1,350, deposit of one month, utilities not included (about $150), no pets, 12-month lease. Hide the problems unless asked directly: 5th floor with no elevator, right next to a fire station.",
    opening: { en: "Hi hi hi! Come in! Oh, I have JUST the place for you. It's cozy, it's charming, it's perfect!", ko: '어머, 어서 와요! 딱 맞는 집이 있어요. 아늑하고, 매력 있고, 완벽해요!' },
    objectives: [
      obj('o1', 'Ask about the rent', '월세 묻기', 'The learner asks about the monthly rent.'),
      obj('o2', 'Ask about the deposit or utilities', '보증금·공과금 묻기', 'The learner asks about the deposit or utilities.'),
      obj('o3', 'Ask about the rules', '계약 조건 묻기', 'The learner asks about pets or the lease length.'),
      obj('b1', 'Uncover a hidden problem', '숨겨진 문제 알아내기', 'The learner asks a question that reveals a hidden problem (no elevator, noise, fire station).', true),
    ],
    phrases: [
      ph('How much is the rent?', '월세가 얼마예요?'),
      ph('Are utilities included?', '공과금 포함인가요?'),
      ph('How much is the deposit?', '보증금은 얼마예요?'),
      ph('Are pets allowed?', '반려동물 키워도 돼요?'),
      ph('Is there anything I should know about the building?', '건물에 대해 알아 둬야 할 게 있나요?'),
    ],
    maxTurns: 10, difficulty: 2, reward: { cash: 120, xp: 100 },
  },
  {
    id: 'car_deal', kind: 'place', placeId: 'dealer', npcId: 'frank',
    title: { en: 'Wheel and Deal', ko: '자동차 흥정' },
    brief: { en: 'A used sedan is listed at $6,000. Negotiate the price down. Win the deal and Frank gives you a 20% coupon for any car here!', ko: '6,000달러짜리 중고 세단이 있어요. 가격을 깎아 보세요. 흥정에 성공하면 이 매장 모든 차에 쓸 수 있는 20% 쿠폰을 받아요!' },
    playerRole: 'a buyer interested in a used silver sedan listed at $6,000 with 80,000 miles',
    setting: 'The Elden Motors lot, flags flapping in the wind.',
    npcBrief: "Sell hard ('This baby practically drives itself'). Add a surprise $500 'documentation fee'. If asked about mileage, accident history or service records, admit it had a minor accident. Lower the price step by step when the buyer gives reasons (mileage, accident, other dealers). Lowest acceptable: $4,800 with no documentation fee.",
    opening: { en: "Well, hello there! Frank Donovan, best deals in town. I see you've got your eye on this beauty!", ko: '어이구, 안녕하세요! 이 동네 최고의 딜러 프랭크 도노번입니다. 이 녀석한테 눈길이 가셨군요!' },
    objectives: [
      obj('o1', "Ask about the car's history", '차량 이력 묻기', 'The learner asks about mileage, accidents or service history.'),
      obj('o2', 'Make a counteroffer', '역제안하기', 'The learner makes a lower offer.'),
      obj('o3', 'Question the extra fee', '추가 수수료 따지기', 'The learner questions or refuses the documentation fee.'),
      obj('b1', 'Get the price under $5,000', '5,000달러 미만으로 합의하기', 'The final agreed price is under $5,000.', true),
    ],
    phrases: [
      ph('Has it ever been in an accident?', '사고 난 적 있어요?'),
      ph("What's the lowest you can go?", '최저 얼마까지 돼요?'),
      ph('I can offer $4,500.', '4,500달러까지 드릴 수 있어요.'),
      ph("What's this documentation fee for?", '이 서류 수수료는 뭐예요?'),
      ph("That's my final offer.", '그게 제 마지막 제안이에요.'),
    ],
    maxTurns: 12, difficulty: 3, reward: { cash: 150, xp: 140 },
    effects: [{ type: 'coupon', id: 'dealer20', discount: 0.2 }],
  },
  {
    id: 'train_ticket', kind: 'place', placeId: 'station', npcId: 'okafor',
    title: { en: 'Ticket to Ride', ko: '기차표 사기' },
    brief: { en: 'Buy a round-trip ticket to Brighton Bay for this Saturday. Find out the time, platform and price.', ko: '이번 토요일 브라이턴 베이행 왕복표를 사세요. 시간, 승강장, 가격을 알아내세요.' },
    playerRole: 'a traveler buying a round-trip train ticket to Brighton Bay for Saturday',
    setting: 'The ticket window at Central Station, the departure board clattering.',
    npcBrief: 'Trains to Brighton Bay leave at 8:15, 11:40 and 15:05 from platform 4; the trip takes 1 hour 50 minutes. One-way $24, round trip $42, 20% off on the off-peak 11:40 train. Ask one-way or round trip, what time and the return date. Share one fun train fact.',
    opening: { en: 'Good morning! Where are you off to today?', ko: '좋은 아침입니다! 오늘은 어디로 가세요?' },
    objectives: [
      obj('o1', 'Ask for a round-trip ticket', '왕복표 요청하기', 'The learner asks for a round-trip ticket to Brighton Bay.'),
      obj('o2', 'Choose a departure time', '출발 시간 고르기', 'The learner chooses a train time.'),
      obj('o3', 'Find out the platform', '승강장 확인하기', 'The learner asks about or confirms the platform.'),
      obj('b1', 'Get the off-peak discount', '할인 받기', 'The learner asks about discounts or chooses the off-peak train.', true),
    ],
    phrases: [
      ph('A round-trip ticket to Brighton Bay, please.', '브라이턴 베이 왕복 한 장 주세요.'),
      ph('What time does the next train leave?', '다음 기차는 몇 시에 떠나요?'),
      ph('Which platform does it leave from?', '몇 번 승강장이에요?'),
      ph('Are there any cheaper tickets?', '더 싼 표 있어요?'),
      ph('How long does the trip take?', '얼마나 걸려요?'),
    ],
    maxTurns: 9, difficulty: 1, reward: { cash: 90, xp: 80 },
  },
  {
    id: 'movie_night', kind: 'place', placeId: 'cinema', npcId: 'zoe',
    title: { en: 'Movie Night', ko: '영화 보는 밤' },
    brief: { en: 'Buy two tickets for tonight. Get a recommendation — without spoilers — and grab some snacks.', ko: '오늘 밤 영화표 두 장을 사세요. 스포일러 없이 추천을 받고 간식도 챙기세요.' },
    playerRole: 'a moviegoer buying two tickets for tonight',
    setting: 'The Starlight Cinema ticket counter, smelling of popcorn.',
    npcBrief: "Tonight: 'Galaxy Drift' (sci-fi action, 7:30 and 9:45), 'Love in Lisbon' (romantic comedy, 8:00), 'The Last Heist' (thriller, 9:00, almost sold out). Tickets $13; popcorn combo with two drinks $15. Recommend with excitement and almost spoil an ending once, then stop yourself. Ask about seat preferences.",
    opening: { en: 'Hi! Welcome to Starlight! What are we watching tonight?', ko: '안녕하세요! 스타라이트에 오신 걸 환영해요! 오늘 밤엔 뭐 보실래요?' },
    objectives: [
      obj('o1', 'Ask for a recommendation', '영화 추천 받기', 'The learner asks what to watch or what is good.'),
      obj('o2', 'Buy two tickets for a showtime', '상영 시간 골라 두 장 사기', 'The learner buys two tickets for a specific movie and time.'),
      obj('o3', 'Choose seats', '좌석 고르기', 'The learner chooses or asks about seats.'),
      obj('b1', 'Order snacks', '간식 주문하기', 'The learner orders popcorn, drinks or a combo.', true),
    ],
    phrases: [
      ph("What's playing tonight?", '오늘 밤 뭐 해요?'),
      ph('What would you recommend? No spoilers, please!', '추천해 줄래요? 스포는 빼고요!'),
      ph('Two tickets for the 9:45 show, please.', '9시 45분 거 두 장 주세요.'),
      ph('Could we sit somewhere in the middle?', '가운데쯤 앉을 수 있을까요?'),
      ph("I'll get the popcorn combo.", '팝콘 콤보로 할게요.'),
    ],
    maxTurns: 9, difficulty: 1, reward: { cash: 90, xp: 80 },
  },
  {
    id: 'taco_order', kind: 'place', placeId: 'foodtruck', npcId: 'carlos',
    title: { en: 'Taco Tuesday', ko: '타코 화요일' },
    brief: { en: 'Order tacos from Carlos, ask about spice levels, and make some small talk.', ko: '카를로스에게 타코를 주문하고, 매운 정도를 묻고, 가볍게 수다를 떨어 보세요.' },
    playerRole: 'a hungry customer at the taco truck in Central Park',
    setting: "Carlos' Taco Truck in Central Park at lunchtime, a short line of office workers.",
    npcBrief: "Menu: carne asada, chicken, fish and veggie tacos ($4 each, 3 for $10). Salsas: mild verde, medium roja and the 'Volcano' (extremely hot). Joke about the Volcano. Love small talk about the city, the weather and football.",
    opening: { en: 'Hola, amigo! Welcome to the best tacos in Elden City! What can I get you?', ko: '올라, 친구! 엘든 시티 최고의 타코에 온 걸 환영해! 뭐 줄까?' },
    objectives: [
      obj('o1', 'Order tacos', '타코 주문하기', 'The learner orders tacos.'),
      obj('o2', 'Ask about the spice level', '매운 정도 묻기', 'The learner asks how spicy the salsa or tacos are.'),
      obj('o3', 'Make small talk', '가벼운 대화 나누기', 'The learner makes small talk (weather, business, city, football).'),
      obj('b1', 'Take the Volcano challenge', '볼케이노 살사 도전', "The learner bravely orders the 'Volcano' salsa.", true),
    ],
    phrases: [
      ph("I'll have three tacos: two chicken and one fish.", '타코 세 개요. 치킨 두 개, 생선 하나요.'),
      ph('How spicy is it?', '얼마나 매워요?'),
      ph('Could I get the salsa on the side?', '살사는 따로 주실래요?'),
      ph('Business looks good today!', '오늘 장사 잘되네요!'),
    ],
    maxTurns: 9, difficulty: 1, reward: { cash: 80, xp: 70 },
  },
  {
    id: 'parking_appeal', kind: 'place', placeId: 'cityhall', npcId: 'harriet',
    title: { en: 'Fight the Ticket', ko: '주차 딱지 이의 신청' },
    brief: { en: 'You got a $120 parking ticket, but the no-parking sign was hidden behind a tree. Appeal it with logic and evidence.', ko: '120달러 주차 딱지를 받았는데 주차 금지 표지판이 나무에 가려져 있었어요. 논리와 증거로 이의를 신청하세요.' },
    playerRole: 'a driver who got a $120 parking ticket on King Street where the no-parking sign was hidden by tree branches; they took photos',
    setting: 'City Hall, the Parking Appeals window. A long form lies on the counter.',
    npcBrief: "Be strict: 'Rules are rules.' Ask for the ticket number, date and location, and the reason for the appeal. Emotional arguments do not work. Clear, logical arguments with evidence (photos of the hidden sign) do: then cancel the ticket and promise to report the tree to the parks department.",
    opening: { en: 'Next. Parking appeals. Ticket number, please.', ko: '다음 분. 주차 이의 신청입니다. 딱지 번호 주세요.' },
    objectives: [
      obj('o1', 'Give the ticket details', '딱지 정보 말하기', 'The learner gives the ticket number, date or location.'),
      obj('o2', 'Explain why the ticket is unfair', '부당한 이유 설명하기', 'The learner explains that the sign was hidden or not visible.'),
      obj('o3', 'Mention your evidence', '증거 제시하기', 'The learner mentions photos or other evidence.'),
      obj('b1', 'Get the ticket canceled', '딱지 취소시키기', 'The clerk agrees to cancel the ticket.', true),
    ],
    phrases: [
      ph("I'd like to appeal this parking ticket.", '이 주차 딱지에 이의를 제기하고 싶어요.'),
      ph('The sign was completely hidden by a tree.', '표지판이 나무에 완전히 가려져 있었어요.'),
      ph('I have photos as evidence.', '증거 사진이 있어요.'),
      ph("I don't think it's fair to fine drivers for a sign they can't see.", '보이지도 않는 표지판으로 벌금을 매기는 건 부당하다고 생각해요.'),
    ],
    maxTurns: 10, difficulty: 3, reward: { cash: 150, xp: 130 },
  },
  {
    id: 'surf_lesson', kind: 'place', placeId: 'beachbar', npcId: 'kai',
    title: { en: 'Catch a Wave', ko: '파도를 잡아라' },
    brief: { en: "Sign up for a surf lesson. Ask about the price, what to bring and whether it's safe for beginners.", ko: '서핑 강습을 신청하세요. 가격, 준비물, 초보자에게 안전한지 물어보세요.' },
    playerRole: 'a beginner who has never surfed before',
    setting: 'Sunset Shack on the beach, reggae music, surfboards leaning on the wall.',
    npcBrief: 'Lessons are 2 hours for $60, board and wetsuit included; bring sunscreen, a towel and swimwear. Next lessons: 4 p.m. today or 9 a.m. tomorrow. Ask about their swimming ability (safety first). Use Aussie slang.',
    opening: { en: "G'day, mate! Welcome to Sunset Shack. Keen for a smoothie, or keen to catch some waves?", ko: '안녕, 친구! 선셋 섁에 온 걸 환영해. 스무디 마실래, 아니면 파도 좀 타 볼래?' },
    objectives: [
      obj('o1', 'Ask about surf lessons', '서핑 강습 문의하기', 'The learner asks about surf lessons.'),
      obj('o2', "Ask about the price and what's included", '가격과 포함 사항 묻기', 'The learner asks about the price or what is included.'),
      obj('o3', 'Book a time', '시간 예약하기', 'The learner books a lesson time.'),
      obj('b1', 'Ask what a slang word means', '슬랭 뜻 물어보기', 'The learner asks the meaning of a slang word Kai used.', true),
    ],
    phrases: [
      ph("I've never surfed before.", '서핑은 처음이에요.'),
      ph('How much is a lesson?', '강습은 얼마예요?'),
      ph('Is the board included?', '보드도 포함이에요?'),
      ph('What should I bring?', '뭘 챙겨 가면 돼요?'),
      ph("Sorry, what does 'keen' mean?", "죄송한데 'keen'이 무슨 뜻이에요?"),
    ],
    maxTurns: 9, difficulty: 1, reward: { cash: 90, xp: 80 },
  },
  {
    id: 'pizza_signup', kind: 'place', placeId: 'pizzeria', npcId: 'tony', once: true,
    title: { en: 'Delivery Driver Wanted', ko: '배달원 구함' },
    brief: { en: "Tony's Pizza needs a delivery driver. Convince Tony you're reliable to unlock pizza delivery jobs.", ko: '토니스 피자가 배달원을 구해요. 믿을 만한 사람이라는 걸 보여 주면 피자 배달 알바가 열려요.' },
    playerRole: 'someone applying for a part-time pizza delivery job',
    setting: "Tony's Pizza, flour everywhere and the oven roaring.",
    npcBrief: "Ask quick questions: Can you drive? Do you know the city? Can you work evenings? What would you do if a customer is angry because the pizza is late? Pay is $12 per delivery plus tips. Hire them if their answers are reasonable, with a warm 'You're hired!'.",
    opening: { en: "You here about the delivery job? Siddown, siddown! So — can you drive?", ko: '배달 일 때문에 왔어? 앉아, 앉아! 그래서 — 운전은 할 줄 알아?' },
    objectives: [
      obj('o1', 'Say you can drive', '운전할 수 있다고 말하기', 'The learner says they can drive.'),
      obj('o2', 'Talk about when you can work', '근무 가능 시간 말하기', 'The learner says when they can work.'),
      obj('o3', 'Explain how you would handle an angry customer', '화난 손님 대처법 말하기', 'The learner explains how they would deal with an angry customer.'),
    ],
    phrases: [
      ph("I'm a careful driver.", '저는 운전을 조심스럽게 해요.'),
      ph('I can work evenings and weekends.', '저녁이랑 주말에 일할 수 있어요.'),
      ph("I'd apologize and stay calm.", '사과하고 침착하게 대응할 거예요.'),
      ph('When can I start?', '언제부터 일할 수 있어요?'),
    ],
    maxTurns: 8, difficulty: 1, reward: { cash: 50, xp: 100 },
    effects: [{ type: 'unlockJob', job: 'pizza' }],
  },
  {
    id: 'cabs_signup', kind: 'place', placeId: 'cabs', npcId: 'lou', once: true,
    title: { en: 'Cab Driver Test', ko: '택시 기사 면접' },
    brief: { en: 'Big Lou needs drivers. Pass his interview to unlock taxi jobs.', ko: '빅 루가 기사를 구해요. 면접을 통과하면 택시 알바가 열려요.' },
    playerRole: 'someone applying to drive a taxi part-time',
    setting: 'The Elden Cabs garage office, a radio crackling with dispatch calls.',
    npcBrief: "Ask about driving experience, how well they know the city, how they'd handle a rude passenger, and a quick quiz: 'A passenger wants the airport — which road do you take?' (Airport Road on the east side is best, but any sensible answer is fine). Drivers keep 70% of the fare plus tips. Hire them if their answers are sensible.",
    opening: { en: 'So you wanna drive a cab, huh? Tell me why I should hire you.', ko: '그래서 택시를 몰고 싶다 이거지? 내가 왜 널 뽑아야 하는지 말해 봐.' },
    objectives: [
      obj('o1', 'Talk about your driving experience', '운전 경력 말하기', 'The learner talks about their driving experience.'),
      obj('o2', 'Explain how you would handle a rude passenger', '무례한 손님 대처법 말하기', 'The learner explains how they would handle a rude passenger.'),
      obj('o3', "Answer Lou's route question", '길 퀴즈 맞히기', 'The learner answers the route question with a reasonable route (ideally Airport Road).'),
    ],
    phrases: [
      ph("I've been driving for five years.", '운전한 지 5년 됐어요.'),
      ph('I know the city pretty well.', '도시를 꽤 잘 알아요.'),
      ph("I'd stay polite and professional.", '예의 바르고 프로답게 대하겠습니다.'),
      ph("I'd take Airport Road.", '공항로로 가겠습니다.'),
    ],
    maxTurns: 8, difficulty: 2, reward: { cash: 50, xp: 100 },
    effects: [{ type: 'unlockJob', job: 'taxi' }],
  },
];

const STREET_SCENARIOS: readonly Scenario[] = [
  {
    id: 'tourist_directions', kind: 'street', npcPool: ['hans', 'yuki', 'maria', 'bob'], context: 'directions',
    title: { en: 'Lost Tourist', ko: '길 잃은 관광객' },
    brief: { en: 'A tourist needs to get to {place}. Check the route on the map and give clear directions.', ko: '관광객이 {place}에 가야 해요. 지도에서 경로를 확인하고 명확하게 길을 알려 주세요.' },
    playerRole: 'a local who knows the way',
    setting: 'A busy sidewalk in Elden City.',
    npcBrief: 'You are lost and want to get to {place}. Listen carefully to the directions. If something is unclear, ask a follow-up (e.g. "Left at which street?" or "Is it far?"). Repeat the directions back to confirm, then thank them warmly.',
    opening: { en: 'Excuse me, sorry to bother you! Do you know how to get to {place}?', ko: '실례합니다, 방해해서 죄송해요! {place}에 어떻게 가는지 아세요?' },
    objectives: [
      obj('o1', 'Say which way to go first', '처음 갈 방향 말하기', 'The learner tells the tourist which way to go first (a street and/or direction).'),
      obj('o2', 'Explain the turns', '어디서 꺾는지 설명하기', 'The learner explains the turns (left/right, which street), or says it is straight ahead.'),
      obj('o3', 'Say where it is at the end', '도착 지점 설명하기', 'The learner says where the destination is at the end (on the left/right, next to…).'),
      obj('b1', 'Give directions that match the route', '실제 경로와 일치하게 안내하기', 'The directions closely match the correct route.', true),
    ],
    phrases: [
      ph('Go straight for two blocks.', '두 블록 직진하세요.'),
      ph('Turn left onto Main Street.', '메인 스트리트에서 왼쪽으로 도세요.'),
      ph("It'll be on your right.", '오른쪽에 있을 거예요.'),
      ph("You can't miss it.", '금방 찾으실 거예요.'),
      ph("It's about a ten-minute walk.", '걸어서 10분 정도예요.'),
    ],
    maxTurns: 8, difficulty: 2, reward: { cash: 60, xp: 70 },
  },
  {
    id: 'fender_bender', kind: 'street', npcPool: ['greg', 'emily', 'walter'], context: 'accident',
    title: { en: 'Fender Bender', ko: '접촉 사고' },
    brief: { en: "You bumped into another car. Check that they're OK, apologize, and exchange insurance information.", ko: '다른 차와 부딪혔어요. 상대방이 괜찮은지 확인하고, 사과하고, 보험 정보를 교환하세요.' },
    playerRole: 'the driver who caused a minor car accident',
    setting: 'The side of the road right after a minor collision, traffic passing by.',
    npcBrief: "React to the accident according to your personality. You want their name, phone number and insurance company. If the learner is responsible and polite, calm down and agree to handle it through insurance. If they blame you or try to leave, get upset.",
    opening: { en: "Hey! What were you doing?! Didn't you see me?", ko: '이봐요! 뭐 하는 거예요?! 저 못 봤어요?' },
    objectives: [
      obj('o1', 'Ask if the other driver is OK', '괜찮은지 묻기', 'The learner asks if the other person is OK or hurt.'),
      obj('o2', 'Apologize', '사과하기', 'The learner apologizes sincerely.'),
      obj('o3', 'Exchange insurance information', '보험 정보 교환하기', 'The learner offers or asks for insurance or contact details.'),
      obj('b1', 'Calm the other driver down', '상대방 진정시키기', 'The other driver calms down thanks to the learner.', true),
    ],
    phrases: [
      ph('Are you OK? Is anyone hurt?', '괜찮으세요? 다친 사람 있어요?'),
      ph("I'm so sorry. It was my fault.", '정말 죄송해요. 제 잘못이에요.'),
      ph("Let's exchange insurance information.", '보험 정보 교환하시죠.'),
      ph("Here's my number.", '여기 제 번호예요.'),
    ],
    maxTurns: 8, difficulty: 2, reward: { cash: 60, xp: 80 },
  },
  {
    id: 'police_stop', kind: 'street', npcId: 'brody', context: 'police',
    title: { en: 'Pulled Over', ko: '경찰 단속' },
    brief: { en: 'The police stopped you. Stay calm, be honest and polite, and explain yourself. Talk well and you might get off with a warning!', ko: '경찰에게 붙잡혔어요. 침착하고 정직하고 예의 바르게 설명하세요. 말을 잘하면 경고로 끝날 수도 있어요!' },
    playerRole: 'a driver who was just pulled over by the police',
    setting: 'The side of the road, police lights flashing blue and red.',
    npcBrief: "You stopped the driver for the offense described below. Ask for license and registration, whether they know why they were stopped, and for an explanation. If they are honest, polite and apologetic, let them go with a warning. If they lie, argue or are rude, say you'll write a ticket.",
    opening: { en: 'License and registration, please. Do you know why I pulled you over?', ko: '면허증과 차량 등록증 주세요. 왜 세웠는지 아세요?' },
    objectives: [
      obj('o1', 'Respond politely to the officer', '경찰에게 예의 있게 응대하기', 'The learner responds politely and cooperates (e.g. hands over their license).'),
      obj('o2', 'Admit or explain what happened', '상황 인정·설명하기', 'The learner honestly explains or admits what happened.'),
      obj('o3', 'Apologize and promise to be careful', '사과하고 조심하겠다고 약속하기', 'The learner apologizes and promises to be more careful.'),
    ],
    phrases: [
      ph("Here's my license, officer.", '여기 면허증입니다, 경관님.'),
      ph("I'm sorry, I didn't realize I was going so fast.", '죄송해요, 그렇게 빨리 달리는 줄 몰랐어요.'),
      ph("It won't happen again.", '다시는 안 그러겠습니다.'),
      ph("I'll be more careful from now on.", '앞으로 더 조심할게요.'),
    ],
    maxTurns: 8, difficulty: 2, reward: { cash: 0, xp: 100 },
  },
  {
    id: 'street_interview', kind: 'street', npcId: 'hannah', context: 'interview',
    title: { en: 'On the Street', ko: '길거리 인터뷰' },
    brief: { en: "A TV reporter wants your opinion on {topic}. Give your opinion with a reason and an example — you're on TV!", ko: 'TV 기자가 "{topic}"에 대한 의견을 물어요. 이유와 예시를 들어 의견을 말하세요. 방송에 나가요!' },
    playerRole: 'a person on the street being interviewed live on TV',
    setting: 'A busy downtown plaza; a camera operator is filming.',
    npcBrief: "Introduce the topic ({topic}) and ask for the learner's opinion. Ask 'Why?' and for an example. Ask one follow-up that gently challenges their view. Keep it snappy and upbeat, then thank them.",
    opening: { en: "Hi! Hannah Lee, ETV News! Got a minute? We're asking people about {topic}. What do you think?", ko: '안녕하세요! ETV 뉴스 해나 리입니다! 잠깐 괜찮으세요? "{topic}"에 대해 시민 의견을 듣고 있어요. 어떻게 생각하세요?' },
    objectives: [
      obj('o1', 'Give your opinion', '의견 말하기', 'The learner clearly states an opinion on the topic.'),
      obj('o2', 'Give a reason', '이유 말하기', 'The learner gives at least one reason.'),
      obj('o3', 'Give an example', '예시 들기', 'The learner gives an example or a personal experience.'),
      obj('b1', 'Respond to the challenge', '반론에 답하기', "The learner responds thoughtfully to the reporter's counter-argument.", true),
    ],
    phrases: [
      ph('In my opinion, …', '제 생각에는…'),
      ph("I think it's a great idea because…", '…라서 좋은 생각이라고 봐요.'),
      ph('For example, …', '예를 들어…'),
      ph('I see your point, but…', '무슨 말씀인지는 알겠지만…'),
      ph('On the other hand, …', '반면에…'),
    ],
    maxTurns: 8, difficulty: 3, reward: { cash: 80, xp: 110 },
  },
  {
    id: 'scam_artist', kind: 'street', npcId: 'vinnie',
    title: { en: 'Too Good to Be True', ko: '너무 좋은 거래' },
    brief: { en: "A smooth talker wants to sell you a 'genuine' designer watch. Refuse firmly but politely, and never give out personal information.", ko: '말솜씨 좋은 사람이 "진품" 명품 시계를 팔려고 해요. 단호하지만 정중하게 거절하고, 개인 정보는 절대 알려 주지 마세요.' },
    playerRole: 'a pedestrian approached by a street scammer',
    setting: 'A downtown street corner; Vinnie opens a coat full of watches.',
    npcBrief: "Try to sell a 'genuine Rolux' watch for $200, then $100, then $50. Use pressure ('only today', 'I'm doing you a favor'). Try to get personal information (phone number, where they're staying, card details). If refused firmly twice, give up dramatically (e.g. 'Fine, fine! Your loss!'). If they ask sharp questions (receipt? why so cheap?), get flustered.",
    opening: { en: 'Psst! Hey, friend! You look like someone with great taste. Wanna see something special?', ko: '쉿! 어이, 친구! 안목 있어 보이는데. 특별한 거 하나 볼래?' },
    objectives: [
      obj('o1', 'Say no clearly', '분명하게 거절하기', 'The learner clearly refuses to buy.'),
      obj('o2', 'Question the deal', '거래 의심하기', 'The learner asks a skeptical question (why so cheap, is it real, receipt).'),
      obj('o3', 'Protect your personal information', '개인 정보 지키기', 'The learner refuses to share personal information when asked.'),
      obj('b1', 'End it politely', '정중하게 대화 끝내기', "The learner politely ends the conversation (e.g. 'Have a nice day')." , true),
    ],
    phrases: [
      ph("No, thank you. I'm not interested.", '아니요, 괜찮아요. 관심 없어요.'),
      ph('Why is it so cheap?', '왜 이렇게 싸요?'),
      ph('Is it real? Do you have a receipt?', '진품이에요? 영수증 있어요?'),
      ph("I'd rather not give out my number.", '번호는 알려 드리고 싶지 않아요.'),
      ph('Sorry, I have to go.', '죄송해요, 가 봐야 해서요.'),
    ],
    maxTurns: 8, difficulty: 2, reward: { cash: 70, xp: 90 },
  },
  {
    id: 'street_chat', kind: 'street', npcPool: [...PASSERBY_IDS], context: 'smalltalk', freeTalk: true,
    title: { en: 'Small Talk', ko: '행인과 스몰토크' },
    brief: { en: 'You stopped a stranger on the street. Just chat — ask questions, share a little about yourself and end it politely.', ko: '길에서 모르는 사람에게 말을 걸었어요. 자유롭게 대화하세요 — 질문하고, 내 이야기도 조금 하고, 정중하게 마무리해요.' },
    playerRole: 'a newcomer to Elden City who starts a casual chat with a stranger',
    setting: 'A sidewalk in Elden City. The learner just said hi to you as you were passing by.',
    npcBrief: 'You are a friendly stranger. Answer naturally, share one small detail about your day, and ask the learner a simple question back. Keep it light, like real small talk between strangers. If the learner says goodbye, wish them a nice day.',
    opening: { en: 'Oh, hi there! Can I help you?', ko: '어, 안녕하세요! 무슨 일이세요?' },
    openingPool: [
      { en: 'Oh, hi there! Can I help you?', ko: '어, 안녕하세요! 무슨 일이세요?' },
      { en: "Hey! Beautiful day, isn't it?", ko: '안녕하세요! 날씨 정말 좋죠?' },
      { en: 'Hi! Sorry, I was miles away. What’s up?', ko: '안녕하세요! 죄송해요, 딴생각하고 있었어요. 무슨 일이에요?' },
      { en: 'Oh, hello! You look a bit new around here. Are you?', ko: '아, 안녕하세요! 이 동네 처음이신 것 같은데, 맞아요?' },
    ],
    objectives: [],
    phrases: [
      ph('Hi! Do you live around here?', '안녕하세요! 이 근처 사세요?'),
      ph("I just moved here. What's good around here?", '막 이사 왔어요. 이 근처에 뭐가 좋아요?'),
      ph('What do you do for fun?', '쉴 때 뭐 하세요?'),
      ph('Nice talking to you. Have a good one!', '얘기 즐거웠어요. 좋은 하루 보내세요!'),
    ],
    maxTurns: 8, difficulty: 1, reward: { cash: 10, xp: 40 },
  },
];

const JOB_SCENARIOS: readonly Scenario[] = [
  {
    id: 'taxi_passenger', kind: 'job', npcPool: ['linda', 'rose', 'tyler', 'jazz', 'sam'], context: 'taxi',
    title: { en: 'Taxi Fare', ko: '택시 손님' },
    brief: { en: 'A passenger got in. Confirm the destination ({place}), chat a little, and tell them the fare estimate (about ${fare}).', ko: '손님이 탔어요. 목적지({place})를 확인하고, 가볍게 대화하고, 예상 요금(약 ${fare})을 알려 주세요.' },
    playerRole: 'a taxi driver',
    setting: "Inside the learner's taxi, stopped at the curb.",
    npcBrief: 'You just got into the taxi and want to go to {place}. Ask how long it will take and how much it costs. Make some small talk that fits your personality. Once the driver has confirmed the destination and fare, say you are ready to go.',
    opening: { en: 'Hi! Can you take me to {place}, please?', ko: '안녕하세요! {place}까지 가 주실 수 있어요?' },
    objectives: [
      obj('o1', 'Greet the passenger', '손님에게 인사하기', 'The learner greets the passenger.'),
      obj('o2', 'Confirm the destination', '목적지 확인하기', 'The learner confirms the destination.'),
      obj('o3', 'Tell the fare or travel time', '요금·소요 시간 안내하기', 'The learner tells the estimated fare or travel time.'),
      obj('b1', 'Make small talk', '가벼운 대화 나누기', 'The learner makes friendly small talk.', true),
    ],
    phrases: [
      ph('Hi there! Where to?', '안녕하세요! 어디로 모실까요?'),
      ph('Sure. Hop in!', '네, 타세요!'),
      ph("It'll take about ten minutes.", '10분 정도 걸릴 거예요.'),
      ph('It should be around $30.', '30달러 정도 나올 거예요.'),
      ph('Are you from around here?', '이 동네 분이세요?'),
    ],
    maxTurns: 6, difficulty: 1, reward: { cash: 0, xp: 50 },
  },
  {
    id: 'pizza_customer', kind: 'job', npcPool: ['max', 'laura', 'harold'], context: 'pizza',
    title: { en: 'Pizza Delivery', ko: '피자 배달' },
    brief: { en: "Hand over the order ({order}), take payment ($38), and keep the customer happy.", ko: '주문한 음식({order})을 전달하고, 결제(38달러)를 받고, 손님 기분을 챙기세요.' },
    playerRole: "a pizza delivery driver from Tony's Pizza",
    setting: "The customer's front door.",
    npcBrief: 'You ordered {order}. The delivery is {late}. React according to your personality (complain if it is late). Check the order, pay $38 by card or cash, and tip based on how the driver treats you.',
    opening: { en: 'Oh, finally! Is that my order?', ko: '아, 드디어! 그거 제 주문이에요?' },
    objectives: [
      obj('o1', 'Greet and confirm the order', '인사하고 주문 확인하기', 'The learner greets the customer and confirms the order.'),
      obj('o2', 'Take payment', '결제 받기', 'The learner tells the total or asks for payment.'),
      obj('o3', 'Handle the customer politely', '정중하게 응대하기', 'The learner stays polite and responds well to any complaint or question.'),
      obj('b1', 'Earn a tip', '팁 받기', 'The customer decides to give a tip because the learner was friendly and professional.', true),
    ],
    phrases: [
      ph("Hi! Delivery from Tony's Pizza.", "안녕하세요! 토니스 피자에서 배달 왔습니다."),
      ph("Here's your order.", '주문하신 음식 나왔습니다.'),
      ph("That'll be $38, please.", '38달러입니다.'),
      ph('Sorry for the wait.', '기다리게 해서 죄송해요.'),
      ph('Enjoy your meal!', '맛있게 드세요!'),
    ],
    maxTurns: 6, difficulty: 1, reward: { cash: 12, xp: 50 },
  },
];

export const SCENARIOS: readonly Scenario[] = [...STORY_SCENARIOS, ...PLACE_SCENARIOS, ...STREET_SCENARIOS, ...JOB_SCENARIOS, ...ROMANCE_SCENARIOS, ...CALL_SCENARIOS];

export const SCENARIO_BY_ID: ReadonlyMap<string, Scenario> = new Map(SCENARIOS.map((s) => [s.id, s]));

export function getScenario(id: string): Scenario {
  const found = SCENARIO_BY_ID.get(id);
  if (!found) throw new Error(`Unknown scenario: ${id}`);
  return found;
}

export function scenariosAtPlace(placeId: string): Scenario[] {
  return PLACE_SCENARIOS.filter((s) => s.placeId === placeId);
}

/** Checks the NPC chosen by the client is allowed for this scenario. */
export function isNpcAllowed(scenario: Scenario, npcId: string): boolean {
  return scenario.npcId ? scenario.npcId === npcId : !!scenario.npcPool?.includes(npcId);
}
